### ISSUE TITLE
On Protocols screen, don't display new rows when clicking save

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#387]

**Comment by annagav** [comment]
Fixed!

**Comment by pdpinch** [comment]
Please verify on scbdev.odl.mit.edu (hopefully the issue still makes sense).
